class Program
    {
        static void Main(string[] args)
        {
            Dictionary<string, string> musics = new Dictionary<string, string>()
            {
                {"Mundos mudos", $"Ligo directo para a caixa de correio só para ouvir a tua voz, Sei que é cena fora mas todo o dia chega a hora em que o lado esquerdo chora quando se lembra de nós A vida corre tranquila, cada vez menos reguila meto guita de parte e a cabeça não vacila tanto Para minha alegria e meu espanto Pode ser que o passado fique por onde deve estar: No pretérito imperfeito, já que não é mais-que- perfeito, Este é um presente que eu aceito Para atingir a tranquilidade Que supostamente se atinge com a nossa idade A verdade é que a saudade do que passou Não é mais que muita... Mas por muita força que faça ela passa por saber que te vivi... Tu deste tudo e eu joguei, arrisquei e perdi Agora, Muda de número, eu mudei o meu, Muda de número, eu mudei o meu, Muda de número, eu mudei o meu, Muda de Mundo que eu mudei o meu. Cada vez que eu ligo tento deixar mensagem mas acabo por nunca arranjar a coragem Necessária Gostava apenas de partilhar contigo o quotidiano habitual Nada que se compare com as correrias doutras alturas e doutros abismos E já que falo por eufemismos Gostava de dizer que ainda gosto bastante de ti... A casa tá diferente, parece digna de gente Dá gosto sentar no sofá com a tv pela frente Comprei uma máquina de café Xpto, bem bonita, azul bebé Ocasionalmente cozinho e bebo o meu vinho E esqueço o fumo que nos dava aquele quentinho Hoje em dia é mais à base do ar condicionado Condicionei a tentação num clima controlado Quero que saibas que tou bem, sei que tu mais ou menos Sempre gostaste de brincar em perigosos terrenos Em relação a isso eu não sei o que fazer E se calhar é por isso mesmo que acabo por não dizer que a verdade é que a saudade do que passou Não é mais que muita... Mas por muita força que faça ela passa por saber que te vivi... Tu deste tudo e eu joguei, arrisquei e perdi Agora, Muda de número, eu mudei o meu, Muda de número, eu mudei o meu, Muda de número, eu mudei o meu, Muda de Mundo que eu mudei o meu.".ToLower() },
                {"Talk", $"I came back to breathe the smoke I've got a system and I'm usin' my head (talk that talk) Close enough to stay afloat But you can sink with all the weight you've been fed (that talk) Pulled and pried A push don't make it right Lost so easily Tell me what you're doin' Top shelf guy, supermarket price Don't think much of me Tell me what you're doin' I want it all Nonstop givin', I like the way you talk (Just do it) Don't hit the wall Can't stop livin', do anything you want (Just do it) Ooh, ooh, ooh (Just do it) ooh-ooh-ooh (Just do it) Precious toys don't work for play They make a killin' sittin' out of the game (talk that talk) Make that choice to be okay There's nothin' to it when you're makin' it rain (that talk) Taking flight, fallin' from a height Sounds the same to me Tell me what you're doin' Eyes shut tight, keepin' out the light (light) Means I disagree Tell me what you're doin' I want it all Nonstop givin', I like the way you talk (Just do it) Don't hit the wall Can't stop livin', do anything you want (Just do it) ooh, ooh, ooh (Just do it) ooh, ooh, ooh (Just do it) Use somethin', prove somethin' Now, now, now Choose somethin', lose somethin' Now, now, now Use somethin', prove somethin' Now, now, now Choose somethin', lose somethin' Now, now, now Do something, do something Do something, do something Do something, do something I want it all Nonstop givin', I like the way you talk (Just do it) Don't hit the wall, can't stop livin' Do anything you want (Just do it) ooh, ooh, ooh (Just do it) ooh, ooh, ooh (Just do it)".ToLower() },
                {"Warm (feat. HAIM)", $"You gotta tell me the reason Why we can't fall in love You gotta tell me the reason (no, no) Why you won't open up Now I'mma send you to heaven Tequila on your tongue You gotta tell me the reason Why we can't fall in love Tell me the reason (yeah) Why we can't fall in love You gotta tell me the reason Why you won't open up Now I'mma send you to heaven Tequila on your tongue You gotta tell me the reason Why we can't fall in love Why, why, why I know you lie What do you want? Fall in love, risk it all Tell me what you want 'Cause I know that you're lonely on your own We're out in L.A. for a month I don't think I can hide my emotions no, no more (uh huh) At late night say you want me, say you're selfish Think about my body, then two-time Say you want her? Do you want her? Doesn't do it like me, no So hot, burn the place down Give you what you need So you gotta tell me the reason Why we can't fall in love You gotta tell me the reason Why you won't open up Now I'mma send you to heaven Tequila on your tongue You gotta tell me the reason Why we can't fall in love Why, why, why I know you lie What do you want? Fall in love, uh huh, risk it all Make me wanna fall in love Baby, make mistakes Hit me with a champagne kiss And now I'm not thinking straight Look at the skyline high I look up, I wish I saw your face I wanna fall in love Jump in the deep end 'Cause deep down, you're d-dying Tell me you're kinda nervous Tell me you feel the same I wish it was more than surface I wish I could feel nothing Come give me everything Burn down and go again So you gotta tell me the reason Why we can't fall in love You gotta tell me the reason Why you won't open up Now I'mma send you to heaven Tequila on your tongue You gotta tell me the reason Why we can't fall in love Ooh, baby (Why, why, why) Tell me, tell me, tell me the reason (Know you lie, what do you want) Tell me, tell me, tell me the reason (Fall in love, risk it all) Tell me the reason You gotta tell me the reason Tell me the reason Tell me the reason Tell me the reason".ToLower() },
                {"Sidelines", $"I'm not afraid of anything at all Not dying in a fire, not being broke again I'm not afraid of living on a fault line 'Cause nothing ever shakes me Nothing makes me cry Not a plane going down In the ocean, I'm drowning Watch the world from the sidelines Had nothing to prove 'Til you came into my life Gave me something to lose Now I know what it feels like To wanna go outside Like the shape of my outline I'm not afraid of going back to school I gave it up the first time, but I'll try again I'm not afraid of getting older Used to fetishize myself Now I'm talking to my house plants Not of being alone In a room full of people Watching the world from the sidelines Had nothing to prove 'Til you came into my life Gave me something to lose Now I know what it feels like To wanna go outside Like the shape of my outline And I used to think You could hear the ocean in a seashell What a childish thing! ".ToLower() },
                {"Jamelia", $"If I can't be the man, tell me what I am Tell me what I'm here for If I can't be the one, tell her what I've done What good can I be for? Did I not do enough to save the two of us? What more could I give her? What more could I do to see her point of view? Why can't I believe her? You got to make the change I can't take you no more These things you know Do go, oh, ohh Oh, Jamelia You got to go away You can't come Oh, ohh You got to make the change I can't take you no more These things you know Do go, oh, ohh Oh, Jamelia You got to go away You can't come Oh, ohh".ToLower() },
                {"Somethinggreater", $"When I met you I was just a child Working through Fears of the night Then you flew Over to my side And then I knew It had always been right To give, to love To stay in touch To give enough To love Until it lasts forever Until it lasts so long Until we're back together I'll be alone Until it lasts forever Until it lasts so long Until we're back together I'll be alone Now I'm leaving you For the both of us To find something new 'Cause we're not enough And all I can do Is to know That we could meet Again, some time When we could be The end Until it lasts forever Until it lasts so long Until we're back together I'll be alone Until it lasts forever Until it lasts so long Until we're back together I'll be alone Until it lasts forever Until it lasts so long Until we're back together I'll be alone Until it lasts forever Until it lasts so long Until we're back together I'll be alone Holding out for something greater Holding out for something else Holding out for something greater Holding out for something else Until it lasts forever (holding out) Until it lasts so long (for something greater) Until we're back together (holding out) I'll be alone (for something else) Until it lasts forever (holding out) Until it lasts so long (for something greater) Until we're back together (holding out) I'll be alone (for something else) Holding out for something greater Holding out for something else Holding out for something greater Holding out for something else Holding out for something greater Holding out for something else Holding out for something greater Holding out for something else Holding out for something greater Holding out for something else Holding out for something greater Holding out for something else".ToLower() },
                {"Arms Tonite", $"I fell in your arms tonight I fell hard in your arms tonight It was nice I died in your arms tonight I slipped through into the afterlife It was nice White light in your arms tonight I lost sight in your arms tonight It was nice And hey, you, don't you think it's kinda cute That I (I) died (died) right inside your arms tonight That I'm fine even after I have died Because it was in your arms I died I cry in the afterlife I cry hard because I have died And you're alive I try to escape afterlife I try hard to get back inside Your arms alive And hey (hey), you (you), don't you think it's kinda cute That I (I) try (try) to escape the afterlife That I (I) try (try) to get back in your arms alive That I died in your arms That I fell hard in your arms I went and died in your arms that night I fell in your arms tonight Suicide in your arms And hey, you, don't you think it's kinda cute That I (I) died (died) right inside your arms tonight That I'm fine even after I have died That I (I) try (try) to escape the afterlife That I (I) try (try) to get back in your arms alive That I died in your arms that night I fell in your arms tonight I died in your arms tonight White light in your arms tonight I fell in your arms tonight".ToLower() },
                {"Lovestained", $"I'll make it better for you (Ah ah) I'll make it better for you (Ah ah) I'll make it better for you I'll make it better I'll make it better You never have to worry about me I'll make it better Baby, there's no pressure This love is made for us, you'll see Fruit gets ripe, and it's love Bite and angels sing up above It's never enough just to say you're lovestained Fruit gets ripe, and it's love Bite and angels like to get rough Tooth and nails when it gets too much You need to make me lovestained You need to make me lovestained And I, I'll make it better for you (Ah ah) I'll make it better for you (Ah ah) I'll make it better for you (You need to make me lovestained) Slipping back into happiness 'Cause you give me more time To live a life that sings like mine You make me drowsy with delight And I'm slipping back into feeling blessed 'Cause you are so damn fine And I'll skip into the sunlight with you And skip back at midnight I, I'll make it better for you (Ah ah) I'll make it better for you (Ah ah) I'll make it better for you (You need to make me lovestained) I, I'll make it better for you (Ah ah) I'll make it better for you (Ah ah) I'll make it better for you (You need to make me lovestained) You need to, you need to You need to make me lovestained, I I, you need to make me lovestained".ToLower() },
                {"Vida Nova", $"Depois de passar, aprovo Penso em vida nova E olhos na paixão antiga Não se esquece Mas sem ti Arrefece Quando me sinto em brasa Volto, lavei a cara Sai o animal à rua Que vergonha! Traz a alma Toda nua Juntei uma mão de culpa E uma colher de teimosia Tens um bolo de rancor Sabes bem Tens poupado No amor Os outros ao de falar sempre É isso que os outros fazem São as vidas a ferver E então? Tens a tua Pra viver Adicionar à playlist Tamanho A A Cifra Imprimir Corrigir ".ToLower() },
                {"Thunder", $"Just a young gun with a quick fuse I was uptight, wanna let loose I was dreaming of bigger things and Wanna leave my own life behind Not a Yes sir, not a follower Fit the box, fit the mold Have a seat in the foyer, take a number I was lightning before the thunder Thunder, thunder Thunder, thun-, thunder Thun-thun-thunder, thunder Thunder, thunder, thun-, thunder Thun-thun-thunder, thunder Thunder, feel the thunder Lightning and the thunder Thunder, feel the thunder Lightning and the thunder Thunder, thunder Thunder Kids were laughing in my classes While I was scheming for the masses Who do you think you are? Dreaming 'bout being a big star They say, You're basic, they say, You're easy You're always riding in the backseat Now I'm smiling from the stage while You were clapping in the nosebleeds Thunder, thunder, thun- Thunder, thun-thun-thunder Thunder, thunder Thunder, thun-, thunder Thun-thun-thunder, thunder Thunder, feel the thunder Lightning and the thunder Thunder, feel the thunder Lightning and the thunder Thunder Thunder, feel the thunder Lightning and the thunder, thunder Thunder, feel the thunder Lightning and the thunder, thunder Thunder, feel the thunder Lightning and the thunder, thunder Thunder, feel the thunder (never give up, never give up) Lightning and the thunder, thunder (never give up, never give up) Thunder, feel the thunder (never give up, never give up) Lightning and the thunder, thunder (never give up) Thunder, thunder, thun- Thunder, thun-thun-thunder, thunder Thunder, thunder, thun- Thunder, thun-thun-thunder, thunder Thunder, thunder, thun- Thunder, thun-thun-thunder, thunder Thunder, thunder, thun-, thunder Thun-thun-thunder, thunder ".ToLower() },
                {"Easy Love", $"EVERY TIME I TRY TO GO OUT I Blow MY MIND WHILE I’M HEARING THIS SONG LOOKING ALL AROUND THEY’RE ALL WATCHING THEIR PHONES TELL ME WHY DON’T YOU GO FAR AWAY YOU SPEND YOUR DAYS PRETENDING TO BE WHAT YOU DON’T KNOW WHY YOU TRY TO GET ME IF YOU DON’T EVEN KNOW THAT YOU LIVE IN A BUBBLE ABOUT TO EXPLODE THAT’S UP TO YOU FUN FUN FUNNY REASON TO BE A DJ ANYBODY CAN GET IT WHEN YOU GOT IT PLEASE SOMEBODY TELL ME HOW YOU GOT IT NOW YOU GOT EASY LOVE WHEN THE SUN GOES DOWN ON THE ROAD YOU LOOK GOOD BUT WHERE IS YOUR BRAIN AT? LOOKING ALL AROUND THEY’RE ALL WATCHING THEIR PHONES BABY SHOOT BABY SHOOT AGAIN CALL MELISSA BEHIND YOUR BACK FUNNY REASONS TO BE A LOSER LIKE A QUEEN YOU LOOK LIKE MANNEQUIN ‘CHIQUI TAN TAN TAN QUE TUMBAN’ I HATE YOUR LACK OF SHAME ANYBODY CAN GET IT WHEN YOU GOT IT PLEASE SOMEBODY TELL ME HOW YOU GOT IT NOW ANYBODY CAN GET IT WHEN YOU GOT IT PLEASE SOMEBODY TELL ME WHEN SHE’S GONNA GO? YOU SPEND YOUR DAYS PRETENDING TO BE WHAT YOU DON’T KNOW WHY YOU TRY TO GET ME IF YOU DON’T EVEN KNOW THAT YOU LIVE IN A BUBBLE ABOUT TO EXPLODE THAT’S UP TO YOU WHAT IF I LOSE CONTROL? HEY LISTEN THEY’RE COMING AROUND BUT YOUR EPHEMERAL FAME WIL FADE OUT AS SOON AS IT CAME HEY LISTEN YOU’RE READY TO GO AS SOON AS YOU GO I’LL BE COMING BACK TO DANCE AGAIN IT’S ENOUGH OH I’M SORRY I’M NOT LOOKING FOR EASY LOVE OH I’M SORRY I’M NOT LOOKING FOR".ToLower() },
                {"Todagente", $"Toda a gente critica o telemóvel do vizinho Mas no fundo toda a gente queria ter um igualzinho Toda a gente grita: todos diferentes todos iguais! Mas se calhar há uns quantos bacanos a mais Toda a gente quer ser solidária Mas na hora da verdade toda a gente desaparece da área Toda a gente quer ser muito moderna Mas a tacanhez essa há-de ser eterna Toda a gente quer fazer algo de original Acabando por copiar aquilo que acham original Toda a gente repara que acabo duas frases da mesma maneira (Se for esse o caso toda a gente caiu na ratoeira) Apenas quero confirmar se estou a receber a devida atenção Da parte de toda a gente que ouve essa canção Toda a gente precisa de parar e relaxar um bocado E eu, como toda a gente, já 'tou stressado Pego no microfone e faço disso o meu talento Por fora, por dentro, mostrando o meu rebento Superficial, composto, direto e indireto Tá-se cool e tá-se bem Entrega-te ao meu som é agora o que convém Toda a gente critica Toda a gente tem muita pica, Mas é na mesa do café que toda a ação fica, Não há dinheiro que pague este sozinho Manda mas é vir mais um cafezinho Toda a gente critica Toda a gente tem muita pica, Mas é na mesa do café que toda a ação fica, Não há dinheiro que pague este sozinho Manda mas é vir mais um cafezinho Toda a gente até compra camisa Mas dessa treta ao fim ao cabo já ninguém precisa Toda a gente fala da situação em Timor Muitos para ganharem algo, e muito poucos por amor Há quem costume falar de revolução Mas a revolução não vai ser transmitida na televisão Ela tem que acontecer dentro de cada um Caso contrário nunca chegaremos a lugar algum Há quem queira resolver os problemas do mundo inteiro De uma só vez, confiante, tal e qual um bom escuteiro Mas enquanto se perseguem tão nobres ideais Esquecemo-nos de limpar os nossos quintais Tentamos combater todos os males da terra Quando afinal é na nossa casa que começa a guerra Toda a gente devia parar de falar olhar para dentro e agir Virgul dá-lhe a seguir Pego no microfone e faço disso o meu talento Por fora, por dentro, mostrando o meu rebento Superficial, composto, direto e indireto Tá-se cool e tá-se bem Entrega-te ao meu som é agora o que convém Toda a gente critica Toda a gente tem muita pica, Mas é na mesa do café que toda a ação fica, Não há dinheiro que pague este sozinho Manda mas é vir mais um cafezinho Toda a gente critica Toda a gente tem muita pica, Mas é na mesa do café que toda a ação fica, Não há dinheiro que pague este sozinho Manda mas é vir mais um cafezinho".ToLower() },
                {"Nice To See You", $"I, I won't come around I wouldn't act your age With no cloud in sight We had predicted rain Eyes down to your nose Ask how my day has been You don't wait for me I'm working late again It was so nice to see you You haven't changed at all Down to the letter I was a boy, I was a boy Ah, is it always the same? It's okay, I'm fine I wait for something to change I'm over the line (I'm over the line) Ah, is it always the same? It's okay, I'm fine I wait for something to change I'm over the line (I'm over the line) We've all been around Working for the light, light, light, light To turn out, wait there Back to the easy life Who's in on the joke? Can't see the funny side Same time next week I'll be a different guy It was so nice to see you Don't be a stranger now You've got my number Give me a call, give me a call Ah, is it always the same? It's okay, I'm fine I wait for something to change I'm over the line (I'm over the line) Why is it always a game? There's no win, no pride Wait for attention to fade It's a cheap design (I'm over the line) Over the line, yep, it's me again I ride them missteps and leave 'em in I'm a Hordak, be my Evil-Lyn Fade to black and the dream begins I left my prison without a sound Ball and chain weigh a thousand pounds Mean no harm, we can pal around At least 'til the ref call out of bounds I don't need the playbook, I wrote one I know this game is a cold one Who can say? I guess we both won Hold up, I know something that's more fun Paid up, working the angles Play moth and see what the flames do Or break off and see when it came true I break all the rules then blame you Both went home with the NK It's two different homes with the same tape It's two different heads in the same space Ultimate test of your game face Ah, is it always the same? It's okay, I'm fine I wait for something to change I'm over the line (I'm over the line) Why is it always a game? There's no win, no pride Wait for attention to fade It's a cheap design (I'm over the line)".ToLower() },
                {"Want you back", $"Some things are long forgotten Some things were never said We were on one endless road But I had a wandering heart I said we were opposite lovers (Said it from the beginning) you kept trying to prove me wrong (Said you'd always see it through) and I know that I ran you down So you ran away with your heart But just know that I want you back Just know that I want you back Just know that I want you, I'll take the fall and the fault in us I'll give you all the love I never gave before I left you Just know that I want you back Just know that I want you back Just know that I want you, I'll take the fall and the fault in us I'll give you all the love I never gave before I left you I know it's hard to hear it And it may never be enough But don't take it out on me now 'Cause I blame it all on myself And I had a fear of forgiveness (Said it from the beginning) I was too proud to say I was wrong (Said you'd always see me through) but all that time is gone No more fearing control, I'm ready for the both of us now So just know that I want you back So just know that I want you back Just know that I want you, I'll take the fall and the fault in us I'll give you all the love I never gave before I left you Just know that I want you back (just know that I want you) Just know that I want you back (just know that I want you) Just know that I want you, I'll take the fall and the fault in us I'll give you all the love I never gave before I left you (just know that I want you back, baby) Just know that I want you back Just know that I want you back Just know that I want you, I'll take the fall and the fault in us (you back) I'll give you all the love I never gave before I left you (you back) Just know that I want you back Just know that I want you back Just know that I want you, I'll take the fall and the fault in us (you back) I'll give you all the love I never gave before I left you (you back) Just know that I want you back Just know that I want you back Just know that I want you I'll take the fall and the fault in us I'll give you all the love I never gave before I left you Just know that I want you back (just know that I want you) Just know that I want you back (just know that I want you) Just know that I want you, I'll take the fall and the fault in us I'll give you all the love I never gave before I left you (just know that I want you back, baby) (Just know that I want you) (Just know that I want you back, baby) I'll take the fall and the fault in us, I'll give you all the love I never gave before I left you (you back)".ToLower() },
                {"Garden Song", $"Someday, I'm gonna live In your house up on the hill And when your skinhead neighbor goes missing I'll plant a garden in the yard then They're gluing roses on a flatbed You should see it, I mean thousands I grew up here 'til it all went up in flames Except the notches in the door frame I don't know when you got taller See our reflection in the water Off a bridge at the Huntington I hopped the fence when I was 17 Then I knew what I wanted And when I grow up, I'm gonna look up From my phone and see my life And it's gonna be just like my recurring dream I'm at the movies I don't remember what I'm seeing The screen turns into a tidal wave Then it's a dorm room like a hedge maze And when I find you You touch my leg, and I insist But I wake up before we do it I don't know how, but I'm taller It must be something in the water Everything's growing in our garden You don't have to know that it's haunted The doctor put her hands over my liver She told me my resentment's getting smaller No, I'm not afraid of hard work I get everything I want I have everything I wanted ".ToLower() },
                {"Home", $"Home, home Home, home She's just what she pleases 'Cause she's happy on her own And she picks up all the pieces She's going home (baby, I'm home, I'm home, I'm home) Yeah, she's going home (baby, I'm home, I'm home, I'm home) Home, home Home, home Baby, I'm home, I'm home, I'm home Baby, I'm home, I'm home She does sleep so easy (home) 'Cause she did it on her own (home) (ow, ow) There's so much she can teach me (home) She's going home (baby, I'm home, I'm home, I'm home) Yeah, she's going home (baby, I'm home, I'm home, I'm home) Yeah, she's better off than she has ever been Now she's made her peace with everything Yeah, she's going home (baby, I'm home, I'm home, I'm home) Yeah, she's going home (baby, I'm home, I'm home, I'm home) Yeah, she's going home (baby, I'm home, I'm home, I'm home) She's coming home (baby, I'm home, I'm home)".ToLower() },
                {"Lightenup", $"Time to lighten up? I don't plan to I don't plan to Time I've given up I don't plan to I don't plan to Every eye is on us Every side is on us Sing it with pride and promise, never cry Never cry, but you know we like it honest You know that's why we bought you I like your style and all But do it right Do it in time Time to lighten up? I don't plan to I don't plan to Time I've given up I don't plan to I don't plan to I need it, I love it The music, the time it takes for the letter to write back Let it go Let it go, 'cause this is the final product Drink it a while and call us Sell it for dimes and dollars There you go Time to lighten up? I don't plan to I don't plan to Time I've given up I don't plan to I don't plan to".ToLower() },
                {"Oh Ana", $"I'll be God I'll be God I'll be God I'll be God, today Hold my head under the bath and breathe away Slit my wrists and watch that blood evaporate Being this Godly can't be good for Ana's safety, Ana hear me I'll play God I'll play God I'll play God I'll play God, today Ante up and play that God a poker game Walk away with all our little God's spare change Playing this God it can't be good for Ana's safety, Ana hear me Oh, Ana, I'll be with you still You are the angel that I couldn't kill I'll fake God I'll fake God I'll fake God I'll fake God today Hop up on a cloud and watch the world decay Ana on my shoulders and we'll laugh away Faking this God it can't be good for Ana's safety Ana hear me, Ana baby, I'm not crazy Oh Ana, oh Ana, oh Ana I'll be with you still You are the angel that I couldn't kill Kill, kill, kill, kill Oh Ana, I'll be with you still You are the angel that I couldn't kill Ana, I'll be with you still You are the angel that I couldn't kill I couldn't kill I couldn't kill I couldn't kill No, I couldn't kill No, I couldn't kill No, I couldn't kill, Ana Oh, Ana ".ToLower() },
                {"Demons", $"When the days are cold And the cards all fold And the saints we see Are all made of gold When your dreams all fail And the ones we hail Are the worst of all And the blood's run stale I wanna hide the truth I wanna shelter you But with the beast inside There's nowhere we can hide No matter what we breed We still are made of greed This is my kingdom come This is my kingdom come When you feel my heat Look into my eyes It's where my demons hide It's where my demons hide Don't get too close It's dark inside It's where my demons hide It's where my demons hide At the curtain's call It's the last of all When the lights fade out All the sinners crawl So they dug your grave And the masquerade Will come calling out At the mess you've made Don't wanna let you down But I am hell-bound Though this is all for you Don't wanna hide the truth No matter what we breed We still are made of greed This is my kingdom come This is my kingdom come When you feel my heat Look into my eyes It's where my demons hide It's where my demons hide Don't get too close It's dark inside It's where my demons hide It's where my demons hide They say it's what you make I say it's up to fate It's woven in my soul I need to let you go Your eyes, they shine so bright I wanna save that light I can't escape this now Unless you show me how When you feel my heat Look into my eyes It's where my demons hide It's where my demons hide Don't get too close It's dark inside It's where my demons hide It's where my demons hide".ToLower() },
                {"Bones", $"Gimme, gimme, gimme some time to think I'm in the bathroom, looking at me Face in the mirror is all I need (ooh) Wait until the reaper takes my life Never gonna get me out alive I will live a thousand million lives (ooh) My patience is waning Is this entertaining? Our patience is waning Is this entertaining? I-I-I got this feeling, yeah, you know Where I'm losing all control 'Cause there's magic in my bones I-I-I got this feeling in my soul Go ahead and throw your stones 'Cause there's magic in my bones Playing with a stick of dynamite There was never gray in black and white There was never wrong 'til there was right (ooh, oh) Feeling like a boulder hurtling Seeing all the vultures circling Burning in the flames I'm working in Turning in a bed that's darkening My patience is waning Is this entertaining? Our patience is waning Is this entertaining? I-I-I got this feeling, yeah, you know Where I'm losing all control 'Cause there's magic in my bones (in my bones) I-I-I got this feeling in my soul Go ahead and throw your stones 'Cause there's magic in my bones 'Cause there's magic in my bones Look in the mirror of my mind Turning the pages of my life Walking the path so many paced a million times Drown out the voices in the air Leaving the ones that never cared Picking the pieces up and building to the sky My patience is waning Is this entertaining? My patience is waning Is this entertaining? I-I-I got this feeling, yeah, you know Where I'm losing all control 'Cause there's magic in my bones (magic in my bones) I-I-I got this feeling in my soul (soul) Go ahead and throw your stones 'Cause there's magic in There goes my mind (I-I-I) Don't mind There goes my mind (there it goes, there it goes) There goes my mind (I-I-I) Don't mind (there it goes) There goes my mind 'Cause there's magic in my bones".ToLower() },
            };

            while (true)
            {
                var input = Console.ReadLine();

                var taskList = new List<Task<string>>();

                for (int i = 0; i < musics.Count; i++)
                {
                    var locali = i;
                    var localTask = Task.Run<string>(() =>
                    {
                        var localMusic = musics.ElementAt(locali);
                        if (localMusic.Value.Equals(input))
                        {
                            return localMusic.Key;
                        }

                        return null;
                    });
                    taskList.Add(localTask);
                }

                Console.WriteLine();
                Task.WhenAll(taskList).Wait();
                foreach (var music in taskList)
                {
                    if (music.Result != null)
                    {
                        Console.WriteLine(music.Result);
                    }
                }
                Console.WriteLine();
                Console.WriteLine();
                Console.WriteLine();
            }
	}
}